export interface Villa {
  id?: string; // Optional if generated by backend

  villaNumber: string;
  roadNumber: string;
  ownerName: string;
  ownerEmail: string;
  contactNumber: string;
  isOccupied: boolean;
}
